version: "3"

services:
  postgres:
    image: my-postgres:latest
    container_name: my-postgres
    build:
      context: ./db-scripts
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

 